<tr class='book'>
               <td>
                <div class=' col-md-1'>
                    <span class="label label-info pull-left">{{book.product}}</span>
                </div>
               </td>


               <td>
                <div class='col-md-1'>
                    <span class="label label-info pull-left">{{book.num}}</span>
                </div>
               </td>

                <td>
                <button>提取</button>
                </td>
</tr>

